# Generated by Django 5.1.6 on 2025-02-28 05:34

import django_lifecycle.mixins
import pyhub.rag.fields.sqlite
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaxLawDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "embedding",
                    pyhub.rag.fields.sqlite.SQLiteVectorField(
                        dimensions=3072, editable=False
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
